# Generated by Django 5.0.2 on 2025-08-07 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField(verbose_name='漢字文章')),
                ('hiragana', models.TextField(blank=True, null=True, verbose_name='ひらがな文章')),
                ('is_converted', models.BooleanField(default=False, verbose_name='ひらがな変換フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章ペア',
                'verbose_name_plural': '文章ペア',
                'db_table': 'text_pairs',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RemoveField(
            model_name='game',
            name='gold_change',
        ),
        migrations.AddField(
            model_name='game',
            name='accuracy',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='game',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='wpm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
