# Generated by Django 5.0.2 on 2025-08-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_gold_change_back_to_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wpm',
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
