# Generated by Django 5.0.2 on 2025-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_user_gold_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['idempotency_key'], name='idx_game_idempotency'),
        ),
    ]
